### ISSUE TITLE
Change background color formatting

### ISSUE THREAD

**Issue by JacobCallahan** [tldr-pages/tldr-python-client#49] opened 2017-11-27 04:09 UTC
The current background color formatting can clash with different terminal emulator color profiles. For example, see the output in this image, which is a screenshot from my terminal (Fedora 27, default emulator, monokai dark color profile).
https://i.imgur.com/EuJTEXL.png
If possible, don't specify a background color, or use general codes which override a user's color profile for a consistent look an all platforms.

**Comment by JacobCallahan** [comment] 2017-11-27 05:05
After experimenting with the color environmental variables, overriding them to use the system default background color (```export TLDR_COLOR_EXAMPLE="green"```), gives me a much better output.
https://i.imgur.com/XkaJgef.png
So with that I'd recommend **not** defaulting to setting colors for the output's background.

**Comment by waldyrious** [comment] 2017-11-28 18:40
Thanks for the report. This has already been addressed in #23 and #32. Unfortunately a new release is pending in order to make these changes available to end users -- see #47. I'll close this issue as a duplicate of #7, but I'll reopen that one to make the current state of affairs clearer.

**Closed by waldyrious** 2017-11-28 18:40 UTC
