### ISSUE TITLE
There is no document when I use the tldr the Second time.

### ISSUE THREAD

**Issue by ramwin** [tldr-pages/tldr-python-client#45] opened 2017-06-29 03:02 UTC
![Picture](https://raw.githubusercontent.com/ramwin/source/master/tldr.png)

I'm using ubuntu 16.04. I tried to upgrade my tldr using `sudo pip3 install --upgrade tldr`, but the problem still exist.

**Comment by waldyrious** [comment] 2017-08-13 14:54
@ramwin this is a duplicate of #31, which is already fixed in the development version (#36). Unfortunately `pip3 install --upgrade tldr` will only provide that fix when a new release is made, which depends on @felixonmars. I'll create an issue for tracking that.

Until then, you can do `pip3 install git+https://github.com/tldr-pages/tldr-python-client.git` to install the dev version. Please confirm if that fixes the issue for you.

**Closed by waldyrious** 2017-08-13 14:54 UTC

**Comment by ramwin** [comment] 2017-08-15 01:21
Sorry, the problem still exists.
![image1](https://www.ramwin.com/media/tldr1.png)![image2](https://www.ramwin.com/media/tldr2.png)
