### ISSUE TITLE
Cache saving empty file and then displaying empty pages

### ISSUE THREAD

**Issue by ViktorBarzin** [tldr-pages/tldr-python-client#48] opened 2017-11-23 12:15 UTC
First of all my environment:
    Kubuntu 17.04
    python3.6
    None of the env variables in the man is set.

Installing the client and running it for the first time fetches the pages correctly and creates s $HOME/.tldr_cache page with the cached command. However the saved file is empty and running the tldr command again with the same parameter yields an empty response. 
`tldr -u` says it is updating cache but does not seem to work.

Workaround for this is to delete the $HOME/.tldr_cache folder 

Oh and by the way it does not seem to take into consideration env variables at all. Whether they are in ~/.bashrc; /etc/environment or other similar place, not taken into consideration.

**Comment by WheresWardy** [comment] 2017-11-23 12:33
From the looks of the code this isn't Python 3-compatible, running with Python 2 works

**Comment by waldyrious** [comment] 2017-11-25 12:53
@ViktorBarzin this sounds like a dupe of #31. Can you please check if that's the case?

**Comment by ViktorBarzin** [comment] 2017-11-25 13:55
Yes it is the same problem. Should have read the old issue before opening this one.
`pip install git+https://github.com/iliakonnov/tldr-python-client.git`
does fix the problem. Guess default version in pip is not updated yet.
Thank you

**Comment by juliohm** [comment] 2017-11-27 05:29
This issue is affecting every single user of the package on Python 3.

**Comment by waldyrious** [comment] 2017-11-28 18:30
Yeah. I suppose it's worth reopening that issue until an actual release is made. I'll close this one as a duplicate, thanks for confirming.

**Closed by waldyrious** 2017-11-28 18:30 UTC
