### ISSUE TITLE
Bug: --markdown flag doesn't work

### ISSUE THREAD

**Issue by CleanMachine1** [tldr-pages/tldr-python-client#174] opened 2021-11-20 23:17 UTC
tldr.py references -m (--markdown) however it isn't implemented.

**Comment by MasterOdin** [comment] 2021-11-21 02:28
Cannot reproduce:

```
mpeveler@Bishop:~/github$ tldr --version
tldr 3.0.0 (Client Specification 1.4)
mpeveler@Bishop:~/github$ tldr -m tar
# tar

> Archiving utility.
> Often combined with a compression method, such as gzip or bzip2.
> More information: <https://www.gnu.org/software/tar>.

- [c]reate an archive and write it to a [f]ile:

`tar cf {{target.tar}} {{file1}} {{file2}} {{file3}}`

- [c]reate a g[z]ipped archive and write it to a [f]ile:

`tar czf {{target.tar.gz}} {{file1}} {{file2}} {{file3}}`

- [c]reate a g[z]ipped archive from a directory using relative paths:

`tar czf {{target.tar.gz}} --directory={{path/to/directory}} .`

- E[x]tract a (compressed) archive [f]ile into the current directory [v]erbosely:

`tar xvf {{source.tar[.gz|.bz2|.xz]}}`

- E[x]tract a (compressed) archive [f]ile into the target directory:

`tar xf {{source.tar[.gz|.bz2|.xz]}} --directory={{directory}}`

- [c]reate a compressed archive and write it to a [f]ile, using [a]rchive suffix to determine the compression program:

`tar caf {{target.tar.xz}} {{file1}} {{file2}} {{file3}}`

- Lis[t] the contents of a tar [f]ile [v]erbosely:

`tar tvf {{source.tar}}`

- E[x]tract files matching a pattern from an archive [f]ile:

`tar xf {{source.tar}} --wildcards "{{*.html}}"`
```

**Comment by MasterOdin** [comment] 2021-11-21 02:29
Nor running it directly from the repo:

```
mpeveler@Bishop:~/github/tldr-python-client$ python3 tldr.py -m tar
# tar

> Archiving utility.
> Often combined with a compression method, such as gzip or bzip2.
> More information: <https://www.gnu.org/software/tar>.

- [c]reate an archive and write it to a [f]ile:

`tar cf {{target.tar}} {{file1}} {{file2}} {{file3}}`

- [c]reate a g[z]ipped archive and write it to a [f]ile:

`tar czf {{target.tar.gz}} {{file1}} {{file2}} {{file3}}`

- [c]reate a g[z]ipped archive from a directory using relative paths:

`tar czf {{target.tar.gz}} --directory={{path/to/directory}} .`

- E[x]tract a (compressed) archive [f]ile into the current directory [v]erbosely:

`tar xvf {{source.tar[.gz|.bz2|.xz]}}`

- E[x]tract a (compressed) archive [f]ile into the target directory:

`tar xf {{source.tar[.gz|.bz2|.xz]}} --directory={{directory}}`

- [c]reate a compressed archive and write it to a [f]ile, using [a]rchive suffix to determine the compression program:

`tar caf {{target.tar.xz}} {{file1}} {{file2}} {{file3}}`

- Lis[t] the contents of a tar [f]ile [v]erbosely:

`tar tvf {{source.tar}}`

- E[x]tract files matching a pattern from an archive [f]ile:

`tar xf {{source.tar}} --wildcards "{{*.html}}"`
```

**Comment by CleanMachine1** [comment] 2021-11-21 18:38
Ah, I think it was added in v3, and the Arch package is still v2

**Comment by CleanMachine1** [comment] 2021-11-21 18:39
```
tldr -v                                                                               
tldr 2.0.0 (Client Specification 1.4)

tldr -m tar                                                   
usage: tldr command [options]
tldr: error: unrecognized arguments: -m

```

**Comment by MasterOdin** [comment] 2021-11-21 19:02
Yup, it was a feature added in v3. Closing this as this is a downstream issue.

**Closed by MasterOdin** 2021-11-21 19:02 UTC
Labels: bug
