### ISSUE TITLE
No internet connection detected. Please reconnect and try again.

### ISSUE THREAD

**Issue by Eva-Sanya** [tldr-pages/tldr-python-client#57] opened 2018-04-03 21:09 UTC
Keep getting this error on OSX high sierra on command prompt. The session has internet connectivity and i'm able to get to it.

Any help will be appreciated. Thanks.

-m

**Comment by JacobCallahan** [comment] 2018-04-04 13:40
This is likely a duplicate of #56. If you agree, please close this and add your comment there.

**Comment by TimothyBramlett** [comment] 2018-06-11 15:33
Same problem.  Will look at #56

**Comment by zdroid** [comment] 2020-04-29 19:03
Closing this as it's identical to #56.

**Closed by zdroid** 2020-04-29 19:03 UTC
